name       : kteatime
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kteatime-17.08.1.tar.xz : f71385747f7519780816419838ee9ac78af91d7956bf9912897c2cc3e6bc3123
license    : GPL-2.0
component  : desktop
summary    : KTeaTime is a handy timer for steeping tea.
description: |
    KTeaTime is a handy timer for steeping tea. No longer will you have to guess at how long it takes for your tea to be ready. Simply select the type of tea you have, and it will alert you when the tea is ready to drink.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
