name       : kteatime
version    : 18.04.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kteatime-18.04.0.tar.xz : 43d627994d70ea61f0f17a5e256b0d42daecc0fd82b36d612c17a360309ba46a
license    : GPL-2.0
component  : desktop
optimize   : lto
summary    : KTeaTime is a handy timer for steeping tea.
description: |
    KTeaTime is a handy timer for steeping tea. No longer will you have to guess at how long it takes for your tea to be ready. Simply select the type of tea you have, and it will alert you when the tea is ready to drink.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
