name       : kteatime
version    : 19.08.1
release    : 27
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kteatime-19.08.1.tar.xz : a4b80c5ca6f48c1d291a9502c43293cd0aa383f2e089b9435b02ff79b317c310
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop
summary    : KTeaTime is a handy timer for steeping tea
description: |
    KTeaTime is a handy timer for steeping tea. No longer will you have to guess at how long it takes for your tea to be ready. Simply select the type of tea you have, and it will alert you when the tea is ready to drink.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
