name       : kteatime
version    : 17.12.1
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kteatime-17.12.1.tar.xz : e663fa9a4c3d8a07b66a5afcad1c515bb8518fbae051d14d35c259ad261e797f
license    : GPL-2.0
component  : desktop
optimize   : lto
summary    : KTeaTime is a handy timer for steeping tea.
description: |
    KTeaTime is a handy timer for steeping tea. No longer will you have to guess at how long it takes for your tea to be ready. Simply select the type of tea you have, and it will alert you when the tea is ready to drink.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
