name       : kteatime
version    : 17.12.2
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/kteatime-17.12.2.tar.xz : 697f6ca620b8c030303ab88c17e5d309d19b761fc39d568f732e13c3e2d9e18e
license    : GPL-2.0
component  : desktop
optimize   : lto
summary    : KTeaTime is a handy timer for steeping tea.
description: |
    KTeaTime is a handy timer for steeping tea. No longer will you have to guess at how long it takes for your tea to be ready. Simply select the type of tea you have, and it will alert you when the tea is ready to drink.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
