name       : kteatime
version    : 17.04.0
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kteatime-17.04.0.tar.xz : 1c6ea73c621120d5bc91eab4cb6bd284ac8ea30ae73a4272ac24e2b324637466
license    : GPL-2.0
component  : desktop
summary    : KTeaTime is a handy timer for steeping tea.
description: |
    KTeaTime is a handy timer for steeping tea. No longer will you have to guess at how long it takes for your tea to be ready. Simply select the type of tea you have, and it will alert you when the tea is ready to drink.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcrash-devel
    - kdoctools-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
    - ktextwidgets-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
